name: CI

on:
  push:
  pull_request:

jobs:
  coverage:
    name: Coverage for ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: Swatinem/rust-cache@v1
        with:
          key: coverage-cargo-${{ matrix.os }}
        continue-on-error: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Setup virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run coverage
        run: |
          source venv/bin/activate
          source <(cargo llvm-cov show-env --export-prefix)
          cargo llvm-cov --package=foobar clean --workspace
          cargo test --package=foobar
          maturin develop
          pytest tests --cov=foobar --cov-report xml
          cargo llvm-cov --package=foobar --no-run --lcov --output-path coverage.lcov
      - uses: codecov/codecov-action@v3
        with:
          file: coverage.lcov
          name: ${{ matrix.os }}
